FROM python:3.11
# Copy the source files from the host to the container
COPY . /app
RUN mkdir /logs && ln -s /logs /app/logs
# Set the working directory to the app directory
WORKDIR /app
RUN pip install .
