name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "/usr/libexec/docker/cli-plugins" >> $GITHUB_PATH
      - name: Setup test dirs
        run: |
          ./test/createTestDirectories.sh && ./test/createTestFiles.sh
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./test/docker-compose.yml"
      - name: Setup SSH keys
        run: |
          ./test/setupSSHKeys.sh
        continue-on-error: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        continue-on-error: true
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Test with pytest
        run: |
          pytest
        continue-on-error: true
