name: Unit Tests

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          checkName: "Python Lint"
          plugins: flake8-bugbear pep8-naming flake8-use-fstring flake8-black flake8-isort
      - run: echo "/usr/libexec/docker/cli-plugins" >> $GITHUB_PATH
      - name: Setup test dirs
        run: |
          ./test/createTestDirectories.sh && ./test/createTestFiles.sh
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./test/docker-compose.yml"
      - name: Setup SSH keys
        run: |
          ./test/setupSSHKeys.sh
      - name: Test with pytest
        run: |
          pytest
